package server.misaka.service.dto;

import lombok.Data;

import java.io.Serializable;
import java.lang.Long;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The dto of the table "t_bank_card_issuer".
 * @author Kahle
 * @date 2021-09-13T14:10:35.213+0800
 */
@Data
public class BankCardIssuerDTO implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 主键
     */
    private Long id;
    /**
     * 银行名称
     */
    private String bankName;
    /**
     * 机构代码
     */
    private String organizationCode;
    /**
     * 银行卡名称
     */
    private String bankCardName;
    /**
     * 银行卡类型
     */
    private String bankCardType;
    /**
     * 银行卡号长度
     */
    private String bankCardNumberLength;
    /**
     * 发卡机构标识码
     */
    private String issuerIdentificationNumber;
    /**
     * 备注
     */
    private String remark;
    /**
     * 创建者ID
     */
    private String creatorId;
    /**
     * 创建时间
     */
    private Date createTime;
    /**
     * 更新者ID
     */
    private String updaterId;
    /**
     * 更新时间
     */
    private Date updateTime;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2021-09-13T14:10:35.656+0800. */

    /**
     * 银行卡号
     */
    private String bankCardNumber;

}
