package server.misaka.service.dto;

import lombok.Data;

import java.io.Serializable;
import java.lang.Long;
import java.util.Date;
import java.lang.String;
import java.lang.Integer;

/**
 * The dto of the table "t_event_record".
 * @author Kahle
 * @date 2021-09-14T17:16:12.277+0800
 */
@Data
public class EventRecordDTO implements Serializable {

    /* (Start) This will be covered, please do not modify. */
    /**
     * 事件记录ID
     */
    private Long id;
    /**
     * 事件标识
     */
    private String eventCode;
    /**
     * 事件时间
     */
    private Date eventTime;
    /**
     * 独特的ID
     */
    private String distinctId;
    /**
     * 匿名的ID
     */
    private String anonymousId;
    /**
     * 摘要
     */
    private String summary;
    /**
     * 客户端的ID
     */
    private String clientId;
    /**
     * 客户端的应用的ID
     */
    private String clientAppId;
    /**
     * 客户端的设备的ID
     */
    private String clientDeviceId;
    /**
     * 客户端的用户代理
     */
    private String clientUserAgent;
    /**
     * 客户端的网络地址
     */
    private String clientNetAddress;
    /**
     * 被访问的接口的ID
     */
    private String interfaceId;
    /**
     * 服务器的ID
     */
    private String serverId;
    /**
     * 服务器的应用的ID
     */
    private String serverAppId;
    /**
     * 属性JSON
     */
    private String propertiesJson;
    /**
     * 创建者
     */
    private String creatorId;
    /**
     * 创建时间
     */
    private Date createTime;
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2021-09-14T17:16:12.747+0800. */

}
