package server.misaka.persistence.mapper;

import server.misaka.persistence.entity.BankCardIssuer;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * BankCardIssuerMapper.
 * @author Kahle
 * @date 2021-09-13T14:10:35.213+0800
 */
@Mapper
public interface BankCardIssuerMapper {

    /* (Start) This will be covered, please do not modify. */
    /**
     * Insert.
     * @param record The object to insert
     * @return Number of rows effected
     */
    int insert(BankCardIssuer record);

    /**
     * Insert batch.
     * @param recordList A list of records to insert
     * @return Number of rows effected
     */
    int insertBatch(@Param("recordList") List<BankCardIssuer> recordList);

    /**
     * Insert selective.
     * @param record The object to insert
     * @return Number of rows effected
     */
    int insertSelective(BankCardIssuer record);

    /**
     * Delete by primary key.
     * @param id Primary key
     * @param updaterId Current operator
     * @return Number of rows effected
     */
    int deleteByPrimaryKey(@Param("id") Long id, @Param("updaterId") String updaterId);

    /**
     * Delete by primary key list.
     * @param idList Primary key list
     * @param updaterId Current operator
     * @return Number of rows effected
     */
    int deleteByPrimaryKeyList(@Param("idList") List<Long> idList, @Param("updaterId") String updaterId);

    /**
     * Delete selective.
     * @param record Delete conditions
     * @return Number of rows effected
     */
    int deleteSelective(BankCardIssuer record);

    /**
     * Update by primary key.
     * @param record Content to be updated
     * @return Number of rows effected
     */
    int updateByPrimaryKey(BankCardIssuer record);

    /**
     * Update by primary key selective.
     * @param record Content to be updated
     * @return Number of rows effected
     */
    int updateByPrimaryKeySelective(BankCardIssuer record);

    /**
     * Conditional counting.
     * @param record Query condition
     * @return Count result
     */
    int countSelective(BankCardIssuer record);

    /**
     * Query by primary key.
     * @param id Primary key
     * @return Query result
     */
    BankCardIssuer queryByPrimaryKey(@Param("id") Long id);

    /**
     * Query by primary key list.
     * @param idList Primary key list
     * @return Query result list
     */
    List<BankCardIssuer> queryByPrimaryKeyList(@Param("idList") List<Long> idList);

    /**
     * Find one.
     * @param record Query condition
     * @return Query result
     */
    BankCardIssuer findOne(BankCardIssuer record);

    /**
     * Query selective.
     * @param record Query condition
     * @return Query result list
     */
    List<BankCardIssuer> querySelective(BankCardIssuer record);
    /* (End) This will be covered, please do not modify. */
    /* Generated by artoria-extend in 2021-09-13T14:10:35.555+0800. */

}
